import { useState, useCallback, useRef } from "react";

type ConversationStatus = "idle" | "connecting" | "connected" | "disconnected";

export type CoachMode = "explain" | "gaps" | "exam" | "debate";

export type DebateSide = "for" | "against";

/** Exam style mode: which exam to scope to. Empty/null = auto-detect from user's words. */
export type ExamType = "HKDSE" | "IELTS" | "TOEFL" | "ISO" | "";

export interface CoachContext {
  topics?: { id: string; label: string }[];
  knowledgeGaps?: string[];
  studyPlan?: string[];
  /** Debate mode: the motion/topic to argue */
  debateMotion?: string;
  /** Debate mode: which side the user is arguing */
  debateSide?: DebateSide;
  /** Exam style mode: which exam (HKDSE/IELTS/TOEFL/ISO). Empty = auto-detect. */
  examType?: ExamType;
}

interface UseConversationProps {
  onConnect?: () => void;
  onDisconnect?: () => void;
  onError?: (error: unknown) => void;
  onMessage?: (message: unknown) => void;
  /** When set, coach prompts are driven by synthesis context and mode */
  coachContext?: CoachContext | null;
  coachMode?: CoachMode;
  /** When set, coach messages are generated by this async function instead of hardcoded lines */
  getCoachMessage?: (messageIndex: number) => Promise<string | undefined>;
}

interface UseConversationReturn {
  status: ConversationStatus;
  isSpeaking: boolean;
  startSession: (options: { signedUrl: string }) => Promise<string | undefined>;
  endSession: () => Promise<void>;
  sendMessage: (message: string) => void;
  /** Request the next coach reply (used when user has spoken; only for non-debate modes). */
  requestCoachReply: () => Promise<void>;
}

function buildAgentMessages(
  context: CoachContext | null | undefined,
  mode: CoachMode | undefined
): string[] {
  const topics = context?.topics ?? [];
  const labels = topics.map((t) => t.label);
  const gaps = context?.knowledgeGaps ?? [];
  const plan = context?.studyPlan ?? [];

  if (labels.length === 0 && gaps.length === 0) {
    const firstByMode =
      mode === "gaps"
        ? "Hi! We're in Teach Back Gaps mode. I'll have you explain things in your own words and we'll fill any gaps together. Try summarizing something you've been learning."
        : mode === "exam"
          ? "Hi! We're in Exam Style mode. I'll ask you to explain as if in a test. When you're ready, give a short definition or explanation of any topic you know."
          : mode === "debate"
            ? "Welcome to debate mode. Tell me your motion and side when you're ready, or we can use a default. You'll have prep time then a timed opening."
            : "Hi! We're in Explain Topics mode. I'll explain concepts and answer your questions. Tell me a topic you're learning, or start by explaining it in your own words.";
    return [
      firstByMode,
      "Try summarizing one of your key topics in your own words.",
      "Great. Now tell me one thing that still feels confusing.",
      "Nice work. You're getting clearer every time you explain it.",
    ];
  }
  if (mode === "gaps" && gaps.length > 0) {
    const first = gaps[0];
    return [
      "Hi! Let's focus on filling your knowledge gaps.",
      `First, try teaching back: "${first}" in your own words.`,
      gaps.length > 1 ? `Good. Now explain another gap: "${gaps[1]}".` : "Now summarize how this connects to the rest of the material.",
      "Well done. Keep revisiting these until they feel solid.",
    ];
  }
  if (mode === "exam" && labels.length > 0) {
    const topic = labels[0];
    return [
      "Exam-style practice. I'll ask you to explain as if in a test.",
      `Define or explain: ${topic}.`,
      labels.length > 1 ? `Next: how does ${topic} relate to ${labels[1]}?` : "How would you apply this in a problem?",
      "Solid. Practice explaining under time pressure to build exam confidence.",
    ];
  }
  if (mode === "debate") {
    const motion = (context as CoachContext).debateMotion?.trim() || "This house believes that practice makes perfect.";
    const side = (context as CoachContext).debateSide === "against" ? "against" : "for";
    return [
      `Welcome to debate mode. The motion is: "${motion}". You are arguing ${side} the motion. You have one minute to prepare. When I say "Time", give your opening statement.`,
      "Time. You have three minutes for your opening. Begin.",
      "Thirty seconds remaining.",
      "Time's up. Thank you. I'll give you brief feedback on your argumentation shortly.",
    ];
  }
  if (labels.length > 0) {
    return [
      "Hi! Let's practice explaining your key topics.",
      `Start by explaining: ${labels[0]}.`,
      labels.length > 1 ? `Great. Now explain ${labels[1]} in your own words.` : "Now connect this topic to something you already know.",
      plan.length > 0 ? `One study tip: ${plan[0]}. Keep going.` : "Nice work. You're getting clearer every time you explain it.",
    ];
  }
  return [
    "Hi! Let's practice explaining what you're learning.",
    "Try summarizing one of your key topics in your own words.",
    "Great. Now tell me one thing that still feels confusing.",
    "Nice work. You're getting clearer every time you explain it.",
  ];
}

export const useConversation = ({
  onConnect,
  onDisconnect,
  onError,
  onMessage,
  coachContext,
  coachMode = "explain",
  getCoachMessage,
}: UseConversationProps): UseConversationReturn => {
  const [status, setStatus] = useState<ConversationStatus>("disconnected");
  const [isSpeaking, setIsSpeaking] = useState<boolean>(false);
  const sessionRef = useRef<{ timeouts?: ReturnType<typeof setTimeout>[] } | null>(null);
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const nextCoachIndexRef = useRef(0);

  const startSession = useCallback(
    async (options: { signedUrl: string }) => {
      console.log("Starting session with signed URL (mock):", options.signedUrl);
      setStatus("connecting");

      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }

      nextCoachIndexRef.current = 0;
      const fallbackMessages = buildAgentMessages(coachContext, coachMode);
      // First message (index 0) fires immediately so the coach welcomes first.
      // Non-debate: only schedule this one; later messages when user speaks (requestCoachReply).
      // Debate: intro 0, prep ~15s then "Time. Begin", 30s at 45s, time's up at 60s
      const delays =
        coachMode === "debate"
          ? [0, 15000, 45000, 60000]
          : [0, 20000, 38000, 56000];

      timeoutRef.current = setTimeout(() => {
        setStatus("connected");
        onConnect?.();

        const timeouts: ReturnType<typeof setTimeout>[] = [];
        const indicesToSchedule =
          coachMode === "debate" ? [0, 1, 2, 3] : [0];
        indicesToSchedule.forEach((i) => {
          const fallbackMsg = fallbackMessages[i] ?? "";
          const t = setTimeout(async () => {
            setIsSpeaking(true);
            let msg = fallbackMsg;
            if (getCoachMessage) {
              try {
                const dynamic = await getCoachMessage(i);
                if (dynamic && dynamic.trim()) msg = dynamic.trim();
              } catch {
                // keep fallback
              }
            }
            onMessage?.(msg);
            nextCoachIndexRef.current = i + 1;
            setTimeout(() => setIsSpeaking(false), 500);
          }, delays[i] ?? 2000 + i * 18000);
          timeouts.push(t);
        });

        sessionRef.current = { timeouts };
      }, 1000);

      return "mock-conversation-id";
    },
    [onConnect, onMessage, coachContext, coachMode, getCoachMessage],
  );

  const endSession = useCallback(async () => {
    console.log("Ending session (mock)...");

    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
      timeoutRef.current = null;
    }

    if (sessionRef.current?.timeouts) {
      sessionRef.current.timeouts.forEach(clearTimeout);
    }

    setIsSpeaking(false);
    setStatus("disconnected");
    sessionRef.current = null;

    await new Promise((resolve) => setTimeout(resolve, 300));
    onDisconnect?.();
  }, [onDisconnect]);

  const sendMessage = useCallback(
    (message: string) => {
      if (status === "connected") {
        console.log("Sending message to mock agent:", message);
        onMessage?.(message);
      }
    },
    [status, onMessage],
  );

  const requestCoachReply = useCallback(async () => {
    if (status !== "connected" || !getCoachMessage) return;
    const idx = nextCoachIndexRef.current;
    const fallbackMessages = buildAgentMessages(coachContext, coachMode);
    const fallbackMsg = fallbackMessages[idx] ?? "";
    setIsSpeaking(true);
    let msg = fallbackMsg;
    try {
      const dynamic = await getCoachMessage(idx);
      if (dynamic && dynamic.trim()) msg = dynamic.trim();
    } catch {
      // keep fallback
    }
    onMessage?.(msg);
    nextCoachIndexRef.current = idx + 1;
    setTimeout(() => setIsSpeaking(false), 500);
  }, [status, coachContext, coachMode, getCoachMessage, onMessage]);

  return {
    status,
    isSpeaking,
    startSession,
    endSession,
    sendMessage,
    requestCoachReply,
  };
};

